//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// --------------------------------------------------------------------------------------------------
// <auto-generatedInfo>
// 	This code was generated by ResW File Code Generator (http://reswcodegen.codeplex.com)
// 	ResW File Code Generator was written by Christian Resma Helle
// 	and is under GNU General Public License version 2 (GPLv2)
// 
// 	This code contains a helper class exposing property representations
// 	of the string resources defined in the specified .ResW file
// 
// 	Generated: 08/30/2014 19:23:35
// </auto-generatedInfo>
// --------------------------------------------------------------------------------------------------
namespace Microsoft.Journal
{
    using Windows.ApplicationModel.Resources;
    
    
    public partial class AppResources
    {
        
        private static ResourceLoader resourceLoader;
        
        static AppResources()
        {
            string executingAssemblyName;
            executingAssemblyName = Windows.UI.Xaml.Application.Current.GetType().AssemblyQualifiedName;
            string[] executingAssemblySplit;
            executingAssemblySplit = executingAssemblyName.Split(',');
            executingAssemblyName = executingAssemblySplit[1];
            string currentAssemblyName;
            currentAssemblyName = typeof(AppResources).AssemblyQualifiedName;
            string[] currentAssemblySplit;
            currentAssemblySplit = currentAssemblyName.Split(',');
            currentAssemblyName = currentAssemblySplit[1];
            if (executingAssemblyName.Equals(currentAssemblyName))
            {
                resourceLoader = ResourceLoader.GetForCurrentView("AppResources");
            }
            else
            {
                resourceLoader = ResourceLoader.GetForCurrentView(currentAssemblyName + "/AppResources");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Listening..."
        /// </summary>
        public static string ListeningText
        {
            get
            {
                return resourceLoader.GetString("ListeningText");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "You will need to accept the speech privacy policy in order to use speech recognition in this app."
        /// </summary>
        public static string SpeechPrivacyPolicyError
        {
            get
            {
                return resourceLoader.GetString("SpeechPrivacyPolicyError");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "There was a problem starting in-app speech recognition. The details are provided below.
        ///
        ///HResult: {0:X} : {1}"
        /// </summary>
        public static string SpeechRecognitionErrorTemplate
        {
            get
            {
                return resourceLoader.GetString("SpeechRecognitionErrorTemplate");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "<speak version='1.0' xmlns='http://www.w3.org/2001/10/synthesis' xml:lang="en-US">
        ///    <prosody pitch='+35%' rate='-10%'> Adam's temperature</prosody> is now over <prosody pitch='+15%' >one hundred </prosody>  degrees.  I assume you want to <prosody pitch='+15%'>pick him up</prosody> from daycare. Would you like me to <prosody pitch='+15%' >cancel</prosody> your meetings and call a <prosody pitch='+15%' >taxi ?</prosody>
        ///</speak>"
        /// </summary>
        public static string SpokenAlertMessage
        {
            get
            {
                return resourceLoader.GetString("SpokenAlertMessage");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "<speak version='1.0' xmlns='http://www.w3.org/2001/10/synthesis' xml:lang="en-US"> <prosody pitch='+15%' rate='-10%'> Let </prosody> me check </speak>"
        /// </summary>
        public static string SpokenCheckSsmlTemplate
        {
            get
            {
                return resourceLoader.GetString("SpokenCheckSsmlTemplate");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "<speak version='1.0' xmlns='http://www.w3.org/2001/10/synthesis' xml:lang="en-US"> <prosody pitch='+35%' rate='-10%'> Adam's </prosody> <prosody pitch='-15%'> temperature </prosody> is <prosody pitch='+15%' rate='-10%'>slightly</prosody> elevated.  There is a <prosody pitch='+15%' rate='-10%'>seventy</prosody> percent chance he will reach <prosody pitch='+15%' rate='-10%'>one hundred</prosody> degrees in a few hours.</speak>"
        /// </summary>
        public static string SpokenResultSsmlTemplate
        {
            get
            {
                return resourceLoader.GetString("SpokenResultSsmlTemplate");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "<speak version='1.0' xmlns='http://www.w3.org/2001/10/synthesis' xml:lang="en-US"> <prosody pitch='+35%' rate='-10%'> Searching </prosody> <prosody pitch='-15%'> for: </prosody> {0} </speak>"
        /// </summary>
        public static string SpokenSearchSsmlTemplate
        {
            get
            {
                return resourceLoader.GetString("SpokenSearchSsmlTemplate");
            }
        }
    }
}
